#!/usr/bin/expect -f
set hostname [lindex $argv 0]
set user [lindex $argv 1]
set passwd [lindex $argv 2]
set port [lindex $argv 3]
set timeout 300
set force_conservative 1
if {$force_conservative} {
  set send_slow {128 .1}
}
spawn ssh -p $port $user@$hostname;
expect {
    "*continue connecting (yes/no)?" { send -s "yes\r"; exp_continue }
    "*assword:" {
        send -s "$passwd\r";
    }
}
interact


## alias in .bashrc 
## alias h256='~/host-ssh/ssh_expect ip username passwd port'
